service: serverless-dotnet

provider:
  name: aws
  runtime: dotnet6
  stage: dev

package:
  artifact: bin/Release/net6.0/serverless-dotnet.zip

functions:
  app:
    handler: serverless-dotnet::serverless_dotnet.LambdaEntryPoint::FunctionHandlerAsync
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
